window.TEXAS_CORNERS_LOCATIONS = [
  {
    name: 'Texas Drive Park',
    cat: 'Park',
    type: 'park',
    icon: 'fa-solid fa-tree',
    address: '6603 Texas Dr, Kalamazoo, MI 49009',
    lat: 42.2071,
    lng: -85.6785,
    url: '/Parks%20and%20Facilities/texas_drive_park.html',
    img: '/Pictures/texas_drive_park.jpg'
  },
  {
    name: 'Maple Hill Splash Pad',
    cat: 'Park',
    type: 'park',
    icon: 'fa-solid fa-water',
    address: '6603 Texas Dr, Kalamazoo, MI 49009',
    lat: 42.2073,
    lng: -85.6783,
    url: '/Parks%20and%20Facilities/maple_hill_splash_pad.html',
    img: '/Pictures/maple_hill_splash_pad.jpg'
  },
  {
    name: '6th Street Park',
    cat: 'Park',
    type: 'park',
    icon: 'fa-solid fa-tree',
    address: '6321 S 6th St, Kalamazoo, MI 49009',
    lat: 42.2259,
    lng: -85.7016,
    url: '/Parks%20and%20Facilities/6th_street_park.html',
    img: '/Pictures/6th_street_park.jpg'
  },
  {
    name: 'Pocket Park',
    cat: 'Park',
    type: 'park',
    icon: 'fa-solid fa-seedling',
    address: '7110 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2009,
    lng: -85.6893,
    url: '/Parks%20and%20Facilities/pocket_park.html',
    img: '/Pictures/pocket_park.jpg'
  },
  {
    name: 'Texas Township Trailway',
    cat: 'Trail',
    type: 'park',
    icon: 'fa-solid fa-person-hiking',
    address: '7930 S 8th St, Kalamazoo, MI 49009',
    lat: 42.2069,
    lng: -85.6787,
    url: '/Parks%20and%20Facilities/texas_township_trailway.html',
    img: '/Pictures/texas_township_trailway.jpg'
  },
  {
    name: 'Farmers Market Pavilion',
    cat: 'Facility',
    type: 'park',
    icon: 'fa-solid fa-store',
    address: '7110 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2010,
    lng: -85.6894,
    url: '/Parks%20and%20Facilities/farmers_market_pavilion.html',
    img: '/Pictures/farmers_market_provilion.jpg'
  },
  {
    name: 'Al Sabo Land Preserve',
    cat: 'Preserve',
    type: 'park',
    icon: 'fa-solid fa-leaf',
    address: '6310 Texas Dr, Kalamazoo, MI 49009',
    lat: 42.2241,
    lng: -85.6668,
    url: '/Parks%20and%20Facilities/al_sabo_land_preserve.html',
    img: '/Pictures/al_sabo_land_preserve.jpg'
  },
  {
    name: 'Woollam Nature Preserve',
    cat: 'Preserve',
    type: 'park',
    icon: 'fa-solid fa-leaf',
    address: '6278 Texas Dr, Kalamazoo, MI 49009',
    lat: 42.2087,
    lng: -85.6775,
    url: '/Parks%20and%20Facilities/woollam_nature_preserve.html',
    img: '/Pictures/woollam_nature_preserve.jpg'
  },
  {
    name: 'Texas Corners Brewing',
    cat: 'Brewery',
    type: 'food',
    icon: 'fa-solid fa-beer-mug-empty',
    address: '6970 Texas Dr, Kalamazoo, MI 49009',
    lat: 42.2024,
    lng: -85.6866,
    url: '/Food/texas_corners_brewing.html',
    img: '/Pictures/texas_corners_brewing.jpeg'
  },
  {
    name: 'Bold',
    cat: 'Restaurant',
    type: 'food',
    icon: 'fa-solid fa-utensils',
    address: '6915 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2003,
    lng: -85.6852,
    url: '/Food/bold.html',
    img: '/Pictures/bold.jpg'
  },
  {
    name: 'Gusto',
    cat: 'Restaurant',
    type: 'food',
    icon: 'fa-solid fa-utensils',
    address: '6997 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2006,
    lng: -85.6869,
    url: '/Food/gusto.html',
    img: '/Pictures/gusto.jpg'
  },
  {
    name: 'Sura Korean BBQ',
    cat: 'Korean BBQ',
    type: 'food',
    icon: 'fa-solid fa-fire-burner',
    address: '6909 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2003,
    lng: -85.6851,
    url: '/Food/sura.html',
    img: '/Pictures/sura.jpg'
  },
  {
    name: "Fletcher's Pub",
    cat: 'Bar & Grill',
    type: 'food',
    icon: 'fa-solid fa-whiskey-glass',
    address: '7177 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2004,
    lng: -85.6859,
    url: '/Food/fletchers_pub.html',
    img: '/Pictures/fletchers_pub.jpg'
  },
  {
    name: "Louie's Corner Bar",
    cat: 'Bar',
    type: 'food',
    icon: 'fa-solid fa-whiskey-glass',
    address: '7177 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2012,
    lng: -85.6908,
    url: '/Food/louies_corner_bar.html',
    img: '/Pictures/louies_corner_bar.webp'
  },
  {
    name: 'Rykse & Co',
    cat: 'Restaurant',
    type: 'food',
    icon: 'fa-solid fa-utensils',
    address: '7141 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2010,
    lng: -85.6900,
    url: '/Food/rykse_and_co.html',
    img: '/Pictures/rykse_and_co.webp'
  },
  {
    name: 'Biggby Coffee',
    cat: 'Coffee',
    type: 'food',
    icon: 'fa-solid fa-mug-hot',
    address: '8016 Vineyard Pkwy, Kalamazoo, MI 49009',
    lat: 42.2008,
    lng: -85.6835,
    url: '/Food/biggby_coffee.html',
    img: '/Pictures/biggby_coffee.jpg'
  },
  {
    name: 'Holy Taco',
    cat: 'Restaurant',
    type: 'food',
    icon: 'fa-solid fa-utensils',
    address: '6942 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2004,
    lng: -85.6858,
    url: '/Food/holy_taco.html',
    img: '/Pictures/holy_taco.jpg'
  },
  {
    name: 'Hunan Garden',
    cat: 'Restaurant',
    type: 'food',
    icon: 'fa-solid fa-utensils',
    address: '7157 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2011,
    lng: -85.6903,
    url: '/Food/hunan_garden.html',
    img: '/Pictures/hunan_gardens.jpg'
  },
  {
    name: "Hungry Howie's Pizza",
    cat: 'Pizza',
    type: 'food',
    icon: 'fa-solid fa-pizza-slice',
    address: '7949 S 8th St, Kalamazoo, MI 49009',
    lat: 42.2021,
    lng: -85.6867,
    url: '/Food/hungry_howies_pizza.html',
    img: '/Pictures/hungry_howies_pizza.jpg'
  },
  {
    name: "Zeb's Trading Company",
    cat: 'Restaurant',
    type: 'food',
    icon: 'fa-solid fa-utensils',
    address: '7990 S 8th St, Kalamazoo, MI 49009',
    lat: 42.2014,
    lng: -85.6872,
    url: '/Food/zebs_trading_company.html',
    img: '/Pictures/zebs_trading_company.jpg'
  },
  {
    name: "VS Bogey's & Stogies",
    cat: 'Golf & Cigars',
    type: 'business',
    icon: 'fa-solid fa-golf-ball-tee',
    address: '7117 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2010,
    lng: -85.6895,
    url: '/Buisnesses/vs_bogeys_and_stogies.html',
    img: '/Pictures/vs_bogeys_and_stogies.jpg'
  },
  {
    name: 'Texas Corners Ace Hardware',
    cat: 'Hardware',
    type: 'business',
    icon: 'fa-solid fa-wrench',
    address: '7129 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2010,
    lng: -85.6897,
    url: '/Buisnesses/texas_corners_ace_hardware.html',
    img: '/Pictures/texas_corners_ace_hardware.jpg'
  },
  {
    name: 'Allure Skin & Beauty',
    cat: 'Beauty',
    type: 'business',
    icon: 'fa-solid fa-spa',
    address: '7067 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2008,
    lng: -85.6884,
    url: '/Buisnesses/allure_skin_and_beauty.html',
    img: '/Pictures/allure_skin_and_beauty.jpg'
  },
  {
    name: 'Lee & Birch',
    cat: 'Boutique',
    type: 'business',
    icon: 'fa-solid fa-bag-shopping',
    address: '7047 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2007,
    lng: -85.6880,
    url: '/Buisnesses/lee_and_birch_kalamazoo.html',
    img: '/Pictures/lee_and_birch_kalamazoo.jpg'
  },
  {
    name: 'The Cheese Lady',
    cat: 'Specialty Food',
    type: 'business',
    icon: 'fa-solid fa-cheese',
    address: '7035 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2007,
    lng: -85.6878,
    url: '/Buisnesses/the_cheese_lady.html',
    img: '/Pictures/the_cheese_lady.jpg'
  },
  {
    name: 'Pink Lemonade',
    cat: "Children's Boutique",
    type: 'business',
    icon: 'fa-solid fa-bag-shopping',
    address: '7039 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2007,
    lng: -85.6879,
    url: '/Buisnesses/pink_lemonade.html',
    img: '/Pictures/pink_lemonade.jpg'
  },
  {
    name: "Refined Men's Grooming",
    cat: 'Grooming',
    type: 'business',
    icon: 'fa-solid fa-scissors',
    address: '6997 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2005,
    lng: -85.6870,
    url: '/Buisnesses/refined_mens_grooming.html',
    img: '/Pictures/refined_mens_grooming.jpeg'
  },
  {
    name: 'VCA Animal Hospital',
    cat: 'Veterinary',
    type: 'business',
    icon: 'fa-solid fa-paw',
    address: '7075 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2008,
    lng: -85.6886,
    url: '/Buisnesses/vca_texas_corners_animal_hospital.html',
    img: '/Pictures/vca_texas_corners_animal_hospital.jpg'
  },
  {
    name: 'KLH Custom Homes',
    cat: 'Home Builder',
    type: 'business',
    icon: 'fa-solid fa-house',
    address: '7058 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2008,
    lng: -85.6882,
    url: '/Buisnesses/klh_custom_homes.html',
    img: '/Pictures/klh_custom_homes.jpg'
  },
  {
    name: "Dave's Glass Service",
    cat: 'Glass & Auto',
    type: 'business',
    icon: 'fa-solid fa-car',
    address: '8136 Shooting Star Ln, Kalamazoo, MI 49009',
    lat: 42.1989,
    lng: -85.6892,
    url: '/Buisnesses/daves_glass_service.html',
    img: '/Pictures/daves_glass.jpg'
  },
  {
    name: 'Citgo',
    cat: 'Gas Station',
    type: 'business',
    icon: 'fa-solid fa-gas-pump',
    address: '7019 W Q Ave, Kalamazoo, MI 49009',
    lat: 42.2007,
    lng: -85.6874,
    url: '/Buisnesses/citgo.html',
    img: '/Pictures/citgo.jpg'
  }
];
